fix jenkins

diff --git a/deployment/Jenkinsfile b/deployment/Jenkinsfile
--- a/deployment/Jenkinsfile
+++ b/deployment/Jenkinsfile
@@ -46,24 +46,11 @@ pipeline {
     }
 
     stages {
-        stage('Configure credentials'){
-            steps {
-                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-key', keyFileVariable: 'private_key', usernameVariable: 'username')]) {
-                    script {
-                        remote.name = "${params.HOST}"
-                        remote.host = "${params.HOST}"
-                        remote.user = "${username}"
-                        remote.identity = readFile "${private_key}"
-                        remote.allowAnyHosts = true
-                    }
-                }
-            }
-        }
-
+      //Клонирую репо на jenkins-agent
         stage('Checkout repo'){
             steps {
                 script {
-                    ssh """
+                    sh """
                         set -ex; set -o pipefail
                         test -d ${env.PRJ_DIR} || git clone ${env.GIT_URL} ${env.PRJ_DIR}
                         cd ${env.PRJ_DIR}
@@ -73,7 +60,7 @@ pipeline {
                 }
             }
         }
-
+    //Собираю образ на jenkins-agente
         stage('Build image') {
             when {
                 expression { params.RUN_TEST && !params.ROLLBACK }
@@ -84,23 +71,10 @@ pipeline {
                 """
             }
         }
-
-        stage('Push image'){
-            when {
-                expression { !params.ROLLBACK }
-            }
-            steps {
-                sh """
-                    docker login -u ${env.REPO_USER} -p ${env.DOCKER_TOKEN}
-                    docker push ${env.DOCKER_REPO}:${BUILD_NUMBER}
-                    docker logout
-                """
-            }
-        }
-
+    //Тестирую этот образ на jenkins-agente
         stage('Run tests'){
             when {
-                expression { !params.ROLLBACK }
+                expression { params.RUN_TEST && !params.ROLLBACK }
             }
             steps {
                 warnError('Test failed'){
@@ -134,16 +108,66 @@ pipeline {
                             ${env.DOCKER_REPO}:${BUILD_NUMBER}
                         sleep 10
                         docker exec backend python -m pytest tests_app.py -v --disable-warnings --maxfail=1
+                        docker rm -f backend db
+                        docker network rm tests
                     """
                 }
             }
         }
-
-        stage('Prepare envs'){
+    //Пушу собранный образ с jenkins-agenta в свой dockerhub
+        stage('Push image'){
             when {
                 expression { !params.ROLLBACK }
             }
             steps {
+                sh """
+                    docker login -u ${env.REPO_USER} -p ${env.DOCKER_TOKEN}
+                    docker push ${env.DOCKER_REPO}:${BUILD_NUMBER}
+                    docker logout
+                """
+            }
+        }
+    //Настраиваю параметры для удаленного подключения для деплоя
+        stage('Configure credentials'){
+            when {
+                expression { !params.ROLLBACK }
+            }
+            steps {
+                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-key', keyFileVariable: 'private_key', usernameVariable: 'username')]) {
+                    script {
+                        remote.name = "${params.HOST}"
+                        remote.host = "${params.HOST}"
+                        remote.user = "${username}"
+                        remote.identity = readFile "${private_key}"
+                        remote.allowAnyHosts = true
+                    }
+                }
+            }
+        }
+
+        stage('Deploy'){
+            when {
+                expression { !params.ROLLBACK }
+            }
+            steps {
+                sshCommand remote: remote, command: """
+                    set -ex; set -o pipefail
+                    sudo mkdir -p ${env.PRJ_DIR}
+                    sudo chown -R jenkins:jenkins ${env.PRJ_DIR}
+                    mkdir -p ${env.PRJ_DIR}/nginx
+                    mkdir -p ${env.PRJ_DIR}/app
+                    mkdir -p ${env.PRJ_DIR}/app/static
+                """
+                sh """
+                    scp -i \${private_key} compose.yml \
+                    ${remote.user}@${remote.host}:${env.PRJ_DIR}/compose.yml
+
+                    scp -i \${private_key} nginx/bookstore.conf \
+                    ${remote.user}@${remote.host}:${env.PRJ_DIR}/nginx/
+
+                    scp -i \${private_key} app/init_db_sql \
+                    ${remote.user}@${remote.host}:${env.PRJ_DIR}/app/
+                """
                 sshCommand remote: remote, command: """
                     set -ex; set -o pipefail
                     cd ${env.PRJ_DIR}
@@ -161,18 +185,13 @@ pipeline {
                     EOF
                     echo "✅ .env is ready"
                 """
-            }
-        }
-
-        stage('Deploy'){
-            when {
-                expression { !params.ROLLBACK }
-            }
-            steps {
                 sshCommand remote: remote, command: """
-                    set -ex; set -o pipefail
+                    set -ex
                     cd ${env.PRJ_DIR}
+                    docker compose pull
+                    docker compose down || true
                     docker compose up -d
+                    docker compose ps
                 """
             }
         }
@@ -191,6 +210,22 @@ pipeline {
                     docker compose up -d backend --force-recreate
                 """
             }
+        }
+    }
+    post {
+        always {
+            sh """
+                docker system prune -f || true
+            """
+        }
+
+        success {
+            echo "✅ Deploy to ${params.HOST}:8000 success"
+            echo "Image: ${env.DOCKER_REPO}:${env.TAG}"
+        }
+
+        failure {
+            echo "❌ Pipeline failed!"
         }
     }
 }
